[SERVICE]
    flush        1
    daemon       Off
    log_level    error
    parsers_file parsers.conf
    plugins_file plugins.conf
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020
    storage.metrics on

# create folder and add one empty .conf file add custom conf if needed
@INCLUDE C:\Program Files\fluent-bit\conf\conf.d\*.conf

[INPUT]
    Name         winevtlog
    Channels     Application,Security,Setup,System,Windows PowerShell
    ignore_missing_channels true
    DB           winlog.sqlite
    Interval_Sec 1
    Read_Existing_Events false
    Tag           winevtlog
    Mem_Buf_Limit     5MB
    render_event_as_xml true

[FILTER]
    Name      parser
    Match     winevtlog
    Key_Name  System
    Parser    extract_service_name
    Reserve_Data On
    Preserve_Key On

# Filter noisy Security Events
#[FILTER]
#    Name    grep
#    Match   winevtlog
#    Exclude System <EventID *>(4624|4627|4634|4647|4662|4672|4688|4689|4798|4799|5156|5158)</EventID>

[FILTER]
    Name    modify
    Match   winevtlog
    Add     host   ${HOSTNAME}
    Rename  System _raw
    Remove  Message
    Remove  StringInserts

[OUTPUT]
    Name        http
    Match       winevtlog
    Host        SomeIP
    Port        SomePort
    URI         /logpipeline/_bulk
    Format      json_lines
    Header      Content-Type application/json
    net.keepalive Off
    workers 1
    Retry_Limit False
